const moodToSongs = {
    'happy': [
        "Happy - Pharrell Williams",
        "Walking on Sunshine - Katrina & The Waves",
        "I Gotta Feeling - The Black Eyed Peas",
        "Good Vibrations - The Beach Boys",
        "Don't Stop Believin' - Journey",
        "Here Comes the Sun - The Beatles",
        "Three Little Birds - Bob Marley",
        "I'm a Believer - The Monkees",
        "Dancing Queen - ABBA",
        "Best Day of My Life - American Authors",
        "Can't Stop the Feeling! - Justin Timberlake",
        "Good Life - OneRepublic",
        "Send Me on My Way - Rusted Root",
        "Mr. Blue Sky - Electric Light Orchestra",
        "Shake It Off - Taylor Swift",
        "Roar - Katy Perry",
        "Brave - Sara Bareilles",
        "On Top of the World - Imagine Dragons",
        "Celebration - Kool & The Gang",
        "I Feel Good - James Brown",
        "Sunshine - OneRepublic",
        "Lovely Day - Bill Withers",
        "Put Your Records On - Corinne Bailey Rae",
        "Better Together - Jack Johnson",
        "Somewhere Over the Rainbow - Israel Kamakawiwo'ole",
        "What a Wonderful World - Louis Armstrong",
        "You Make My Dreams - Hall & Oates",
        "I'm Yours - Jason Mraz",
        "Life is Beautiful - Sixx:A.M.",
        "Beautiful Day - U2",
        "The Middle - Jimmy Eat World",
        "Float On - Modest Mouse",
        "Keep Your Head Up - Andy Grammer",
        "Rise Up - Andra Day",
        "Unwritten - Natasha Bedingfield",
        "The Power of Love - Huey Lewis and the News",
        "Walking on a Dream - Empire of the Sun",
        "Electric Feel - MGMT",
        "Young Folks - Peter Bjorn and John",
        "Home - Edward Sharpe & The Magnetic Zeros",
        "Ho Hey - The Lumineers",
        "Home - Phillip Phillips",
        "Home - Daughtry",
        "Home - Michael Bublé",
        "Home - Blake Shelton",
        "Home - Dierks Bentley",
        "Home - Three Days Grace",
        "Home - Blue October",
        "Home - The Proclaimers",
        "Home - Foo Fighters"
    ],
    'sad': [
        "Someone Like You - Adele",
        "All of Me - John Legend",
        "Stay With Me - Sam Smith",
        "Say Something - A Great Big World",
        "The Sound of Silence - Simon & Garfunkel",
        "Hurt - Johnny Cash",
        "Yesterday - The Beatles",
        "Tears in Heaven - Eric Clapton",
        "Nothing Compares 2 U - Sinead O'Connor",
        "Everybody Hurts - R.E.M.",
        "Mad World - Gary Jules",
        "The Scientist - Coldplay",
        "Fix You - Coldplay",
        "How to Save a Life - The Fray",
        "Boulevard of Broken Dreams - Green Day",
        "Wake Me Up When September Ends - Green Day",
        "When I Was Your Man - Bruno Mars",
        "All I Want - Kodaline",
        "Let Her Go - Passenger",
        "Skinny Love - Birdy",
        "Gravity - John Mayer",
        "The Night We Met - Lord Huron",
        "I Will Always Love You - Whitney Houston",
        "My Heart Will Go On - Celine Dion",
        "Hallelujah - Jeff Buckley",
        "Creep - Radiohead",
        "No One's Gonna Love You - Band of Horses",
        "The One That Got Away - Katy Perry",
        "Someone You Loved - Lewis Capaldi",
        "Before You Go - Lewis Capaldi",
        "When the Party's Over - Billie Eilish",
        "All Too Well - Taylor Swift",
        "Last Kiss - Taylor Swift",
        "Back to December - Taylor Swift",
        "The Story of Us - Taylor Swift",
        "Dear John - Taylor Swift",
        "All You Had to Do Was Stay - Taylor Swift",
        "I Almost Do - Taylor Swift",
        "We Are Never Ever Getting Back Together - Taylor Swift",
        "Stay Stay Stay - Taylor Swift",
        "Sad Beautiful Tragic - Taylor Swift",
        "The Last Time - Taylor Swift",
        "Begin Again - Taylor Swift",
        "Come Back... Be Here - Taylor Swift",
        "I Wish You Would - Taylor Swift",
        "All You Had to Do Was Stay - Taylor Swift",
        "How You Get the Girl - Taylor Swift",
        "This Love - Taylor Swift",
        "I Know Places - Taylor Swift",
        "Clean - Taylor Swift",
        "You Are in Love - Taylor Swift"
    ],
    'energetic': [
        "Eye of the Tiger - Survivor",
        "Stronger - Kanye West",
        "Can't Hold Us - Macklemore & Ryan Lewis",
        "Shake It Off - Taylor Swift",
        "Uptown Funk - Mark Ronson ft. Bruno Mars",
        "Power - Kanye West",
        "Till I Collapse - Eminem",
        "Lose Yourself - Eminem",
        "Remember the Name - Fort Minor",
        "Not Afraid - Eminem",
        "The Pretender - Foo Fighters",
        "My Songs Know What You Did in the Dark - Fall Out Boy",
        "Centuries - Fall Out Boy",
        "Immortals - Fall Out Boy",
        "Sugar, We're Goin Down - Fall Out Boy",
        "Dance, Dance - Fall Out Boy",
        "This Ain't a Scene, It's an Arms Race - Fall Out Boy",
        "Thnks fr th Mmrs - Fall Out Boy",
        "I Don't Care - Fall Out Boy",
        "The Phoenix - Fall Out Boy",
        "Light 'Em Up - Fall Out Boy",
        "Alone Together - Fall Out Boy",
        "Where Is Your Boy - Fall Out Boy",
        "I've Got a Dark Alley - Fall Out Boy",
        "7 Minutes in Heaven - Fall Out Boy",
        "Sophomore Slump - Fall Out Boy",
        "Champagne for My Real Friends - Fall Out Boy",
        "I Slept With Someone - Fall Out Boy",
        "A Little Less Sixteen Candles - Fall Out Boy",
        "Get Busy Living - Fall Out Boy",
        "XO - Fall Out Boy",
        "Fame < Infamy - Fall Out Boy",
        "You're Crashing - Fall Out Boy",
        "I've Got All This Ringing - Fall Out Boy",
        "Golden - Fall Out Boy",
        "The Take Over - Fall Out Boy",
        "Fame < Infamy - Fall Out Boy",
        "You're Crashing - Fall Out Boy",
        "I've Got All This Ringing - Fall Out Boy",
        "Golden - Fall Out Boy",
        "The Take Over - Fall Out Boy",
        "Fame < Infamy - Fall Out Boy",
        "You're Crashing - Fall Out Boy",
        "I've Got All This Ringing - Fall Out Boy",
        "Golden - Fall Out Boy",
        "The Take Over - Fall Out Boy"
    ],
    'calm': [
        "Weightless - Marconi Union",
        "Claire de Lune - Debussy",
        "River Flows in You - Yiruma",
        "Comptine d'un autre été - Yann Tiersen",
        "Gymnopédie No.1 - Erik Satie",
        "Nocturne in E-flat - Chopin",
        "Moonlight Sonata - Beethoven",
        "Air on the G String - Bach",
        "Für Elise - Beethoven",
        "Prelude in C Major - Bach",
        "The Four Seasons - Vivaldi",
        "Canon in D - Pachelbel",
        "Adagio for Strings - Barber",
        "Nimrod - Elgar",
        "Morning Mood - Grieg",
        "Claire de Lune - Debussy",
        "Arabesque No.1 - Debussy",
        "Reverie - Debussy",
        "La fille aux cheveux de lin - Debussy",
        "Prelude to the Afternoon of a Faun - Debussy",
        "Nocturne No.2 - Chopin",
        "Nocturne No.9 - Chopin",
        "Waltz in A minor - Chopin",
        "Prelude in E minor - Chopin",
        "Fantaisie-Impromptu - Chopin",
        "Moonlight Sonata - Beethoven",
        "Für Elise - Beethoven",
        "Pathétique Sonata - Beethoven",
        "Symphony No.6 - Beethoven",
        "Symphony No.7 - Beethoven",
        "The Four Seasons - Vivaldi",
        "Gloria - Vivaldi",
        "Concerto for Two Cellos - Vivaldi",
        "Concerto for Two Violins - Vivaldi",
        "Concerto for Four Violins - Vivaldi",
        "Canon in D - Pachelbel",
        "Chaconne - Pachelbel",
        "Fugue in D minor - Pachelbel",
        "Toccata in D minor - Pachelbel",
        "Fantasia in D minor - Pachelbel",
        "Adagio for Strings - Barber",
        "Summer Music - Barber",
        "Knoxville: Summer of 1915 - Barber",
        "Dover Beach - Barber",
        "The School for Scandal - Barber",
        "Nimrod - Elgar",
        "Salut d'Amour - Elgar",
        "Chanson de Matin - Elgar",
        "Chanson de Nuit - Elgar",
        "Serenade for Strings - Elgar",
        "Morning Mood - Grieg",
        "Peer Gynt Suite - Grieg",
        "Holberg Suite - Grieg",
        "Lyric Pieces - Grieg",
        "Piano Concerto - Grieg"
    ],
    'angry': [
        "Break Stuff - Limp Bizkit",
        "Given Up - Linkin Park",
        "Bodies - Drowning Pool",
        "Killing in the Name - Rage Against the Machine",
        "Bulls on Parade - Rage Against the Machine",
        "F**k You - CeeLo Green",
        "Fight Song - Rachel Platten",
        "Stronger - Kelly Clarkson",
        "Roar - Katy Perry",
        "Fighter - Christina Aguilera",
        "Survivor - Destiny's Child",
        "Not Ready to Make Nice - Dixie Chicks",
        "Since U Been Gone - Kelly Clarkson",
        "Stronger (What Doesn't Kill You) - Kelly Clarkson",
        "Miss Independent - Kelly Clarkson",
        "Behind These Hazel Eyes - Kelly Clarkson",
        "Because of You - Kelly Clarkson",
        "Walk Away - Kelly Clarkson",
        "Never Again - Kelly Clarkson",
        "Hole - Kelly Clarkson",
        "Addicted - Kelly Clarkson",
        "Gone - Kelly Clarkson",
        "All I Ever Wanted - Kelly Clarkson",
        "I Do Not Hook Up - Kelly Clarkson",
        "My Life Would Suck Without You - Kelly Clarkson",
        "I Don't Hook Up - Kelly Clarkson",
        "Cry - Kelly Clarkson",
        "Don't Let Me Stop You - Kelly Clarkson",
        "Long Shot - Kelly Clarkson",
        "Impossible - Kelly Clarkson",
        "Ready - Kelly Clarkson",
        "I Want You - Kelly Clarkson",
        "If I Can't Have You - Kelly Clarkson",
        "Save You - Kelly Clarkson",
        "Whyyawannabringmedown - Kelly Clarkson",
        "I Forgive You - Kelly Clarkson",
        "Hello - Kelly Clarkson",
        "The Day We Fell Apart - Kelly Clarkson",
        "Let Me Down - Kelly Clarkson",
        "You Love Me - Kelly Clarkson",
        "I Hate Myself for Losing You - Kelly Clarkson",
        "Quiet - Kelly Clarkson",
        "Dark Side - Kelly Clarkson",
        "Honestly - Kelly Clarkson",
        "You Can't Win - Kelly Clarkson",
        "Maybe - Kelly Clarkson",
        "How I Feel - Kelly Clarkson",
        "Anymore - Kelly Clarkson",
        "Let Me Down - Kelly Clarkson",
        "You Love Me - Kelly Clarkson"
    ],
    'romantic': [
        "All of Me - John Legend",
        "Perfect - Ed Sheeran",
        "Just the Way You Are - Bruno Mars",
        "A Thousand Years - Christina Perri",
        "Can't Help Falling in Love - Elvis Presley",
        "At Last - Etta James",
        "Unchained Melody - The Righteous Brothers",
        "Can't Take My Eyes Off You - Frankie Valli",
        "The Way You Look Tonight - Frank Sinatra",
        "Unforgettable - Nat King Cole",
        "When I Fall in Love - Nat King Cole",
        "The First Time Ever I Saw Your Face - Roberta Flack",
        "Your Song - Elton John",
        "Wonderful Tonight - Eric Clapton",
        "Make You Feel My Love - Adele",
        "All of Me - John Legend",
        "Stay With Me - Sam Smith",
        "Thinking Out Loud - Ed Sheeran",
        "Photograph - Ed Sheeran",
        "Perfect - Ed Sheeran",
        "Shape of You - Ed Sheeran",
        "Just the Way You Are - Bruno Mars",
        "Marry You - Bruno Mars",
        "Grenade - Bruno Mars",
        "When I Was Your Man - Bruno Mars",
        "A Thousand Years - Christina Perri",
        "Jar of Hearts - Christina Perri",
        "Human - Christina Perri",
        "Arms - Christina Perri",
        "A Thousand Years (Part 2) - Christina Perri",
        "Can't Help Falling in Love - Elvis Presley",
        "Love Me Tender - Elvis Presley",
        "Are You Lonesome Tonight? - Elvis Presley",
        "It's Now or Never - Elvis Presley",
        "Don't Be Cruel - Elvis Presley",
        "At Last - Etta James",
        "I'd Rather Go Blind - Etta James",
        "Tell Mama - Etta James",
        "Something's Got a Hold on Me - Etta James",
        "I Just Want to Make Love to You - Etta James",
        "Unchained Melody - The Righteous Brothers",
        "You've Lost That Lovin' Feelin' - The Righteous Brothers",
        "Ebb Tide - The Righteous Brothers",
        "Just Once in My Life - The Righteous Brothers",
        "Unchained Melody - The Righteous Brothers",
        "Can't Take My Eyes Off You - Frankie Valli",
        "Sherry - Frankie Valli",
        "Big Girls Don't Cry - Frankie Valli",
        "Walk Like a Man - Frankie Valli",
        "Rag Doll - Frankie Valli",
        "The Way You Look Tonight - Frank Sinatra",
        "Fly Me to the Moon - Frank Sinatra",
        "Strangers in the Night - Frank Sinatra",
        "My Way - Frank Sinatra",
        "New York, New York - Frank Sinatra"
    ],
    'nostalgic': [
        "Sweet Home Alabama - Lynyrd Skynyrd",
        "Sweet Child O' Mine - Guns N' Roses",
        "Bohemian Rhapsody - Queen",
        "Hotel California - Eagles",
        "Stairway to Heaven - Led Zeppelin",
        "Sweet Child O' Mine - Guns N' Roses",
        "Paradise City - Guns N' Roses",
        "Welcome to the Jungle - Guns N' Roses",
        "November Rain - Guns N' Roses",
        "Don't Cry - Guns N' Roses",
        "Bohemian Rhapsody - Queen",
        "We Will Rock You - Queen",
        "We Are the Champions - Queen",
        "Don't Stop Me Now - Queen",
        "Radio Ga Ga - Queen",
        "Hotel California - Eagles",
        "Take It Easy - Eagles",
        "Desperado - Eagles",
        "Take It to the Limit - Eagles",
        "Peaceful Easy Feeling - Eagles",
        "Stairway to Heaven - Led Zeppelin",
        "Whole Lotta Love - Led Zeppelin",
        "Black Dog - Led Zeppelin",
        "Rock and Roll - Led Zeppelin",
        "Immigrant Song - Led Zeppelin",
        "Sweet Home Alabama - Lynyrd Skynyrd",
        "Free Bird - Lynyrd Skynyrd",
        "Simple Man - Lynyrd Skynyrd",
        "Tuesday's Gone - Lynyrd Skynyrd",
        "Gimme Three Steps - Lynyrd Skynyrd",
        "Sweet Child O' Mine - Guns N' Roses",
        "Paradise City - Guns N' Roses",
        "Welcome to the Jungle - Guns N' Roses",
        "November Rain - Guns N' Roses",
        "Don't Cry - Guns N' Roses",
        "Bohemian Rhapsody - Queen",
        "We Will Rock You - Queen",
        "We Are the Champions - Queen",
        "Don't Stop Me Now - Queen",
        "Radio Ga Ga - Queen",
        "Hotel California - Eagles",
        "Take It Easy - Eagles",
        "Desperado - Eagles",
        "Take It to the Limit - Eagles",
        "Peaceful Easy Feeling - Eagles",
        "Stairway to Heaven - Led Zeppelin",
        "Whole Lotta Love - Led Zeppelin",
        "Black Dog - Led Zeppelin",
        "Rock and Roll - Led Zeppelin",
        "Immigrant Song - Led Zeppelin"
    ],
    'focused': [
        "Concentration - John Williams",
        "The Four Seasons - Vivaldi",
        "Moonlight Sonata - Beethoven",
        "Nocturne in E-flat - Chopin",
        "Gymnopédie No.1 - Erik Satie",
        "Claire de Lune - Debussy",
        "River Flows in You - Yiruma",
        "Comptine d'un autre été - Yann Tiersen",
        "Weightless - Marconi Union",
        "Experience - Ludovico Einaudi",
        "Nuvole Bianche - Ludovico Einaudi",
        "Divenire - Ludovico Einaudi",
        "I Giorni - Ludovico Einaudi",
        "Oltremare - Ludovico Einaudi",
        "Primavera - Ludovico Einaudi",
        "Concentration - John Williams",
        "The Four Seasons - Vivaldi",
        "Moonlight Sonata - Beethoven",
        "Nocturne in E-flat - Chopin",
        "Gymnopédie No.1 - Erik Satie",
        "Claire de Lune - Debussy",
        "River Flows in You - Yiruma",
        "Comptine d'un autre été - Yann Tiersen",
        "Weightless - Marconi Union",
        "Experience - Ludovico Einaudi",
        "Nuvole Bianche - Ludovico Einaudi",
        "Divenire - Ludovico Einaudi",
        "I Giorni - Ludovico Einaudi",
        "Oltremare - Ludovico Einaudi",
        "Primavera - Ludovico Einaudi",
        "Concentration - John Williams",
        "The Four Seasons - Vivaldi",
        "Moonlight Sonata - Beethoven",
        "Nocturne in E-flat - Chopin",
        "Gymnopédie No.1 - Erik Satie",
        "Claire de Lune - Debussy",
        "River Flows in You - Yiruma",
        "Comptine d'un autre été - Yann Tiersen",
        "Weightless - Marconi Union",
        "Experience - Ludovico Einaudi",
        "Nuvole Bianche - Ludovico Einaudi",
        "Divenire - Ludovico Einaudi",
        "I Giorni - Ludovico Einaudi",
        "Oltremare - Ludovico Einaudi",
        "Primavera - Ludovico Einaudi",
        "Concentration - John Williams",
        "The Four Seasons - Vivaldi",
        "Moonlight Sonata - Beethoven",
        "Nocturne in E-flat - Chopin",
        "Gymnopédie No.1 - Erik Satie"
    ]
};

function getRandomSongs(mood, count = 5) {
    const songs = moodToSongs[mood] || moodToSongs['happy'];
    const shuffled = [...songs].sort(() => 0.5 - Math.random());
    return shuffled.slice(0, count);
} 